version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
  php:
    image: php:7-fpm
    volumes:
      - ./src:/src
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf