version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    depends_on:
      - php
  php:
    image: php:7-fpm
    build: .
    volumes:
      - ./src:/src
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.35
    build: ./database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysqldb:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --explicit_defaults_for_timestamp
volumes:
  mysqldb:
